# Generated by Django 5.2.5 on 2025-08-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_worker_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('composition', models.TextField(verbose_name='Состав')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('section', models.CharField(verbose_name='Раздел')),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(verbose_name='ФИ'),
        ),
    ]
