# Generated by Django 5.2.5 on 2025-08-09 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_dishesoforder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='dishesoforder',
            options={'verbose_name': 'Блюдо заказа', 'verbose_name_plural': 'Блюда заказов'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section'),
        ),
    ]
