# Generated by Django 5.2.5 on 2025-08-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_section_alter_dishesoforder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
