# Generated by Django 5.2.5 on 2025-08-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_section_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(verbose_name='Название'),
        ),
    ]
