# Generated by Django 5.2.5 on 2025-08-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_order_date_alter_order_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='worker',
            new_name='worker_id',
        ),
    ]
