# Generated by Django 5.2.5 on 2025-08-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_worker_order_worker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='worker_id',
        ),
        migrations.RemoveField(
            model_name='dishesoforder',
            name='order',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
