# Generated by Django 5.2.5 on 2025-08-11 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishesoforder',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
            preserve_default=False,
        ),
    ]
