# Generated by Django 5.2.5 on 2025-08-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_dishesoforder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishesoforder',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
