# Generated by Django 5.2.5 on 2025-08-11 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_order_dishesoforder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishesoforder',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.dish'),
        ),
        migrations.AlterField(
            model_name='dishesoforder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.order'),
        ),
    ]
