# Generated by Django 5.2.5 on 2025-08-11 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_dishesoforder_dish_alter_dishesoforder_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DishesOfOrder',
        ),
    ]
