# Generated by Django 5.2.5 on 2025-08-11 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_dishesoforder'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishesOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.dish')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.order')),
            ],
            options={
                'verbose_name': 'Блюдо заказа',
                'verbose_name_plural': 'Блюда заказов',
            },
        ),
    ]
