# Generated by Django 5.2.5 on 2025-08-12 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_dishesoforder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishesoforder',
            name='dish_title',
            field=models.CharField(default=1, verbose_name='Название блюда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishesoforder',
            name='worker_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.worker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.section'),
        ),
    ]
