# Generated by Django 5.2.5 on 2025-08-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_dishesoforder_dish_title_dishesoforder_worker_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='worker_id',
        ),
        migrations.DeleteModel(
            name='DishesOfOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
