# Generated by Django 5.2.5 on 2025-08-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_order_worker_id_delete_dishesoforder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.worker')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='DishesOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_title', models.CharField(verbose_name='Название блюда')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.dish')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.worker')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.order')),
            ],
            options={
                'verbose_name': 'Блюдо заказа',
                'verbose_name_plural': 'Блюда заказов',
            },
        ),
    ]
