# Generated by Django 5.2.5 on 2025-08-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_order_dishesoforder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='worker_id',
        ),
        migrations.DeleteModel(
            name='DishesOfOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
